/*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Copyright (C) 2026 Lucius
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

namespace fcs_utility
{
    internal enum itemType
    {
        BUILDING,
        CHARACTER,
        WEAPON,
        ARMOUR,
        ITEM,
        ANIMAL_ANIMATION,
        ATTACHMENT,
        RACE,
        LOCATION,
        WAR_SAVESTATE,
        FACTION,
        NULL_ITEM,
        ZONE_MAP,
        TOWN,
        WORLDMAP_CHARACTER,
        CHARACTER_APPEARANCE_OLD,
        LOCATIONAL_DAMAGE,
        COMBAT_TECHNIQUE,
        DIALOGUE,
        DIALOGUE_LINE,
        TECHTREE,
        RESEARCH,
        AI_TASK,
        AI_STATE,
        ANIMATION,
        STATS,
        PERSONALITY,
        CONSTANTS,
        BIOMES,
        BUILDING_PART,
        INSTANCE_COLLECTION,
        DIALOG_ACTION,
        TEMPORARY_INFO,
        MOD_FILENAME,
        PLATOON,
        GAMESTATE_BUILDING,
        GAMESTATE_CHARACTER,
        GAMESTATE_FACTION,
        GAMESTATE_TOWN_INSTANCE_LIST,
        STATE,
        SAVED_STATE,
        INVENTORY_STATE,
        INVENTORY_ITEM_STATE,
        REPEATABLE_BUILDING_PART_SLOT,
        MATERIAL_SPEC,
        MATERIAL_SPECS_COLLECTION,
        CONTAINER,
        MATERIAL_SPECS_CLOTHING,
        GAMESTATE_BUILDING_INTERIOR,
        VENDOR_LIST,
        MATERIAL_SPECS_WEAPON,
        WEAPON_MANUFACTURER,
        SQUAD_TEMPLATE,
        ROAD,
        LOCATION_NODE,
        COLOR_DATA,
        CAMERA,
        MEDICAL_STATE,
        MEDICAL_PART_STATE,
        FOLIAGE_LAYER,
        FOLIAGE_MESH,
        GRASS,
        BUILDING_FUNCTIONALITY,
        DAY_SCHEDULE,
        NEW_GAME_STARTOFF,
        GAMESTATE_CRAFTING,
        CHARACTER_APPEARANCE,
        GAMESTATE_AI,
        WILDLIFE_BIRDS,
        MAP_FEATURES,
        DIPLOMATIC_ASSAULTS,
        SINGLE_DIPLOMATIC_ASSAULT,
        AI_PACKAGE,
        DIALOGUE_PACKAGE,
        GUN_DATA,
        HUMAN_CHARACTER,
        ANIMAL_CHARACTER,
        UNIQUE_SQUAD_TEMPLATE,
        FACTION_TEMPLATE,
        AI_SCHEDULE,
        WEATHER,
        SEASON,
        EFFECT,
        ITEM_PLACEMENT_GROUP,
        WORD_SWAPS,
        NEST,
        NEST_ITEM,
        CHARACTER_PHYSICS_ATTACHMENT,
        LIGHT,
        HEAD,
        BLUEPRINT,
        SHOP_TRADER_CLASS,
        FOLIAGE_BUILDING,
        FACTION_CAMPAIGN,
        GAMESTATE_TOWN,
        BIOME_GROUP,
        EFFECT_FOG_VOLUME,
        FARM_DATA,
        FARM_PART,
        ENVIRONMENT_RESOURCES,
        RACE_GROUP,
        ARTIFACTS,
        MAP_ITEM,
        BUILDINGS_SWAP,
        ITEMS_CULTURE,
        ANIMATION_EVENT,
        TUTORIAL,
        CROSSBOW,
        TERRAIN_DECALS,
        AMBIENT_SOUND,
        WORLD_EVENT_STATE,
        LIMB_REPLACEMENT,
        ANIMATION_FILE,
        ____XXX___,
        OBJECT_TYPE_MAX
    }

    internal class GameData
    {
        internal enum State
        {
            ORIGINAL = 0,
            OWNED = 1,
            MODIFIED = 2,
            LOCKED = 4,
            REMOVED = 8,
            MISSING = 0x10,
            INVALID = 0x20
        }
    }
}
